### ISSUE TITLE
No module named 'redbot'

### ISSUE THREAD

**Issue by wang9811** [HarukiGrande/GrandeCogs-V3#4]
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WIN10\Downloads\관리봇\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\WIN10\Downloads\관리봇\cogs\owner.py", line 950, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('D:\\WIN10\\Downloads\\관리봇\\cogs\\bash\\bash.py', 23, 60, '        await ctx.send(f"```ini\\n\\n[Bash Input]: {arg}\\n```")\n'))
[22/10/2018 18:30] ERROR owner load 74: No module named 'redbot'
Traceback (most recent call last):
  File "D:\WIN10\Downloads\관리봇\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\WIN10\Downloads\관리봇\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "D:\Python 3.5\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\WIN10\Downloads\관리봇\cogs\bash\__init__.py", line 1, in <module>
    from .bash import Bash
  File "D:\WIN10\Downloads\관리봇\cogs\bash\bash.py", line 2, in <module>
    from redbot.core import commands
ImportError: No module named 'redbot'
what's the problem

**Comment by retke** [comment]
This is a repo for V3 cogs and you're using V2. Please upgrade to V3 or install V2 cogs.
